# Generated by Django 3.2.3 on 2021-05-31 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['id'], 'verbose_name': 'Control', 'verbose_name_plural': 'Controles'},
        ),
    ]
