# Generated by Django 3.2.3 on 2021-05-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_alter_control_options'),
        ('incidences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencecontrol',
            options={'ordering': ['id'], 'verbose_name': 'Efectividad del control en la incidencia', 'verbose_name_plural': 'Efectividad de los controles en la incidencia'},
        ),
        migrations.AlterUniqueTogether(
            name='incidencecontrol',
            unique_together={('id', 'incidence', 'control')},
        ),
        migrations.AddIndex(
            model_name='incidencecontrol',
            index=models.Index(fields=['id', 'incidence', 'control'], name='incidences__id_4d4036_idx'),
        ),
    ]
