# Generated by Django 3.2.3 on 2021-05-31 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('incidences', '0002_auto_20210531_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidence',
            old_name='cause',
            new_name='causes',
        ),
    ]
