# Generated by Django 3.2.3 on 2021-06-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('controls', '0002_alter_control_options'),
        ('incidences', '0003_rename_cause_incidence_causes'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='controls',
            field=models.ManyToManyField(related_name='incidences', related_query_name='incidence',
                                         to='controls.Control', verbose_name='Controles Aplicados'),
        ),
        migrations.DeleteModel(
            name='IncidenceControl',
        ),
    ]
