# Generated by Django 3.2.3 on 2021-05-30 02:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del riesgo')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción del riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la consecuencia')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción de la consecuencia')),
                ('economic_loss', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Costo económico')),
                ('risk',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='risk.risk',
                                   verbose_name='Riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la causa')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción de la causa')),
                ('risk',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes', to='risk.risk',
                                   verbose_name='Riesgo')),
            ],
        ),
    ]
